GET http://localhost:3000/employees
###
GET http://localhost:3000/employees/1
###
GET http://localhost:3000/employees/999
###
GET http://localhost:3000/employees/abc
###
POST http://localhost:3000/employees
Content-Type: application/json

{
  "name": "Carlos",
  "position": "Backend Developer",
  "department": "Engineering",
  "salary": 85000
}
###
POST http://localhost:3000/employees
Content-Type: application/json

{
  "name": "Carlos",
  "position": "Backend Developer",
  "salary": 85000
}
###
POST http://localhost:3000/employees
Content-Type: application/json

{
  "position": "Backend Developer",
  "department": "Engineering",
  "salary": 85000
}
###
POST http://localhost:3000/employees
Content-Type: application/json

{
  "name": "Carlos",
  "department": "Engineering",
  "salary": 85000
}
###
POST http://localhost:3000/employees
Content-Type: application/json

{
  "name": "Carlos",
  "position": "Backend Developer",
  "salary": "85000"
}
### id válido + body válido --> 200
PUT http://localhost:3000/employees/1
Content-Type: application/json

{
  "name": "Ana",
  "position": "Senior Backend Developer",
  "department": "Engineering",
  "salary": 100000
}
### id inexistente --> 404
PUT http://localhost:3000/employees/999
Content-Type: application/json

{
  "name": "Ana",
  "position": "Senior Backend Developer",
  "department": "Engineering",
  "salary": 100000
}
### id inválido --> 400
PUT http://localhost:3000/employees/abc
Content-Type: application/json

{
  "name": "Ana",
  "position": "Senior Backend Developer",
  "department": "Engineering",
  "salary": 100000
}
### body inválido --> 400
PUT http://localhost:3000/employees/1
Content-Type: application/json

{
  "name": "Ana",
  "position": "Senior Backend Developer",
  "department": "Engineering",
  "salary": "100000"
}
###

### id válido --> 204
DELETE http://localhost:3000/employees/1

###

### not found --> 404
DELETE http://localhost:3000/employees/999

###

### invalid id --> 400
DELETE http://localhost:3000/employees/abc
